[package]
name = "sqlite-rembed"
license = "MIT OR Apache"
homepage = "https://alexgarcia.xyz/sqlite-rembed"
repo = "https://github.com/asg017/sqlite-rembed"
description = "A SQLite extension for generating text embeddings from remote sources (OpenAI, Cohere, localhost, etc.)"
authors = ["Alex Garcia"]

[targets]
github_releases = {}
sqlpkg = {}
spm = {}
amalgamation = {include=["sqlite-rembed.c", "sqlite-rembed.h"]}

pip = {}
datasette = {}
sqlite_utils = {}

npm = {}

gem = { module_name = "SqliteRembed" }
